stages:
  - setup
  - run

setup-docker:
  stage: setup
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

run-binary:
  stage: test
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
