name: Schedule scraping of openqa.opensuse.org
on:
  push:
    branches:
      - 'o3'
  schedule:
    - cron:  '0 23 * * *'

jobs:
  scrape-o3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code in o3 branch
        uses: actions/checkout@v2
        with:
          ref: o3
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
      
      - name: Build binary
        run: go build -o openQA-module-mapper

      - name: Scrape 
        run: ./openQA-module-mapper &> o3.log

      - name: Commit log
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with: 
          commit_message: Update o3 log

